SelectMission("m5")

SetMissionResetPlayerInCar("m4_talk_car_loc")
SetDynaLoadData("l7z2.p3d;l7r2.p3d;l7r1.p3d;")

UsePedGroup(5)

AddStage(0)
RESET_TO_HERE()
if Mode.IsHard then
	SetMaxTraffic(5)
else
	SetMaxTraffic(3)
end
	SetStageMessageIndex(01)
	SetHUDIcon( "android" )
	AddObjective( "goto" )
		SetDestination( "m5_trailer", "carsphere")
		SetCollectibleEffect("wrench_collect")
		AddNPC("zmale3","m5_zm2_loc")
		AddStageCharacter("wiggum", "", "", "current", "m4_talk_car_loc" )
	CloseObjective()
		if Mode.IsHard then
           SetStageTime(50) AddCondition("timeout") CloseCondition()
		else
           SetStageTime(65) AddCondition("timeout") CloseCondition()
        end
	AddCondition("outofvehicle")
		SetCondTime( 10000 )
	CloseCondition()
	AddCondition( "damage" )
		SetCondMinHealth( 0.0 )
		SetCondTargetVehicle( "current" )
	CloseCondition()
CloseStage()

AddStage(1)
	SetStageMessageIndex(07)
--	SetHUDIcon( "bart" )
	AddObjective("talkto", "neither")
		AddNPC("zmale3", "m5_zm2_loc")
		SetTalkToTarget("zmale3", 0, 0)
	CloseObjective()
CloseStage()

AddStage(0)
	SetStageMessageIndex(12)
	AddObjective("getin")
		SetObjTargetVehicle("current")
	CloseObjective()
	SetStageTime(15)
	AddCondition("timeout")
	CloseCondition()
CloseStage()

AddStage()
if Mode.IsHard then
	SetMaxTraffic(5)
else
	SetMaxTraffic(3)
end
	SetHUDIcon("pwrplant")
	SetStageMessageIndex(04)
	AddStageVehicle("cMedic","m5_medic_carstart","NULL","MedRace/AI_1st.con","jasper")
	AddStageVehicle("ambul","m5_ambul_carstart","NULL","MedRace/AI_2nd.con","jimbo")
	AddObjective("goto")
		SetDestination("power_plant","carsphere")
	CloseObjective()
	SetStageTime(30)
	CloseCondition()
	AddCondition("outofvehicle")
		SetCondTime( 10000 )
	CloseCondition()
	AddCondition( "damage" )
		SetCondMinHealth( 0.0 )
		SetCondTargetVehicle( "current" )
	CloseCondition()
CloseStage()

AddStage()
	SetStageMessageIndex(09)
	AddObjective("goto")
		SetDestination("m5_wig_screwed","triggersphere")
		MustActionTrigger()
		SetCollectibleEffect("none")
	CloseObjective()
CloseStage()

AddStage()
SetStageMessageIndex(10)
	AddObjective("timer")
		SetDurationTime(4)
	CloseObjective()
CloseStage()

AddStage()
DisableHitAndRun()
	SetMaxTraffic(0)
	SetHUDIcon("race")
	SetStageMessageIndex(05)
	AddStageWaypoint( "power_plant" )
	AddStageWaypoint( "m5_waypoint_1" )
	AddStageWaypoint( "m5_waypoint_2" )
	AddStageWaypoint( "m5_waypoint_3" )
	AddStageWaypoint( "m5_waypoint_4" )
		ActivateVehicle("cMedic","NULL","race")
			SetVehicleAIParams( "cMedic", 50, 51 )
			SetStageAIRaceCatchupParams("cMedic", 80, 0.8, 1.11, 1.75) 
		ActivateVehicle("ambul","NULL","race")
			SetVehicleAIParams( "ambul", 50, 51 )
			SetStageAIRaceCatchupParams("ambul", 80, 0.8, 1.11, 1.75) 
	AddObjective("race")
--			AddCollectible("sr4_waypoint2","carsphere")
			SetCollectibleEffect("wrench_collect")
--			AddCollectible("sr4_waypoint3","carsphere")
			SetCollectibleEffect("wrench_collect")
--			AddCollectible("sr4_waypoint4","carsphere")	
			SetCollectibleEffect("wrench_collect")
			AddCollectible("sr4_waypoint5","carsphere")
			SetCollectibleEffect("wrench_collect")
			AddCollectible("sr4_waypoint6","carsphere")
			SetCollectibleEffect("wrench_collect")
			AddCollectible("sr4_waypoint7","carsphere")
			SetCollectibleEffect("wrench_collect")
			AddStageCharacter("wiggum", "", "", "current", "m5_wig_race" )
CloseObjective()
AddCondition("position")
SetConditionPosition(1)
CloseCondition()
AddCondition( "damage" )
	SetCondMinHealth( 0.0 )
	SetCondTargetVehicle( "current")
CloseCondition()
AddCondition("outofvehicle")
	SetCondTime( 10000 )
CloseCondition()
CloseStage()

AddStage()
if Mode.IsHard then
	SetMaxTraffic(5)
else
	SetMaxTraffic(3)
end
	SetStageMessageIndex(01)
	SetHUDIcon( "android" )
	AddObjective( "goto" )
		SetDestination( "m5_trailer", "carsphere")
		SetCollectibleEffect("wrench_collect")
		AddNPC("zmale3","m5_zm2_loc")
	CloseObjective()
	SetStageTime(30)
	AddCondition( "timeout" )
	CloseCondition()
	AddCondition("outofvehicle")
		SetCondTime( 10000 )
	CloseCondition()
	AddCondition( "damage" )
		SetCondMinHealth( 0.0 )
		SetCondTargetVehicle( "current" )
	CloseCondition()
CloseStage()

AddStage()
SetFadeOut(1.5)
	SetStageMessageIndex(08)
--	SetHUDIcon( "bart" )
	AddObjective("talkto", "neither")
		AddNPC("zmale3", "m5_zm2_loc")
		SetTalkToTarget("zmale3", 0, 0)
	CloseObjective()
CloseStage()

AddStage()
	AddObjective("timer")
		SetDurationTime(1.5)
		RemoveNPC("zmale3")
	CloseObjective()
CloseStage()

AddStage("final")
	AddObjective("timer")
		SetDurationTime(1.5)
		AddNPC("male2","m5_zm2_loc")
	CloseObjective()
CloseStage()

CloseMission()